quarkus:
  datasource:
    db-kind: mariadb
     # test_read luego, por ahora test_write
    username: ${datasource.user}
    password: ${datasource.pass}
    jdbc:
      url: jdbc:mariadb://${datasource.host:localhost}:${datasource.port:3306}/${datasource.path}
      # url: jdbc:mariadb://localhost/phylax_quarkus
      max-size: 1
      min-size: 1

app:
  migration:
    db-kind: mariadb
    username: ${datasource.user}
    password: ${datasource.pass}
    group: mysql
    location: db/migration/mysql/changelog.txt
    jdbc:
      url: jdbc:mariadb://${datasource.host:localhost}:${datasource.port:3306}/${datasource.path}
      #Â url: jdbc:mariadb://localhost/phylax_quarkus
